version: "1.0"

parameters:                      
  - name: skipTests
    type: boolean
    default: false

stages:
  - name: Build
    slug: build
    pool:
      name: linux-pool
      filter: "eq(worker.os, 'ubuntu')"
    
    variables:
    - name: KEY_ONE
      value: value_1
    - name: KEY_TWO
      value: value_2
    jobs:
      - name: Compile
        strategy:            
          type: single
        variables:
        - name: GOFLAGS
          value: "-mod=readonly"
        steps:
          - name: Checkout
            type: station-step-builtin.checkout@1
            inputs:
              fetchDepth: 1
          - name: Compile
            type: station-step-builtin.script@1
            working_directory: api
            continue_on_error: false
            condition: "succeeded()"
            env: { CGO_ENABLED: "0" }
            inputs:                   # for type: script (see § Script)
              scriptSource: inline          # inline | package | repository
              syntax: Bash
              scriptBodys: |
                go build -o bin/station ./.

  - name: Tests App
    branchesFilters: 
      branches: main, release/*"
    jobParallelism: 2
    timeout: 60m
    dependsOn: ["build"]
    jobs:
      - name: Testing Job
        continue_on_error: false                # host | container
        strategy:                     # default { type: single }
          type: single                # single | matrix | fanOut
        steps:
          - name: Compile
            type: station-step-builtin.script@1
            working_directory: api
            timeout: 20m
            continue_on_error: false
            condition: "succeeded()"
            env: { CGO_ENABLED: "0" }
            inputs:                   # for type: script (see § Script)
              scriptSource: inline          # inline | package | repository
              syntax: Bash
              scriptBodys: |
                go test -o bin/station ./.

